VideoRentApp/Models/Movie.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace VideoRentApp.Models
{
	public class Movie
	{
		public int MovieId { get; set; }
		public string Title { get; set; }
		public string Description { get; set; }
		public string ImageUrl { get; set; }
		public int Length { get; set; }
		[BindProperty, DataType(DataType.Date)]
		[Display(Name = "Date Release")]
		public DateTime DateRelease { get; set; }
		public string Genre { get; set; }
		[MaxLength(50)]
		[Display(Name = "Main Actress")]
		public string MainActress { get; set; }
		public string ImdbUrl { get; set; }

        public virtual ICollection<RentMovie> RentMovies { get; set; }
    }
}

VideoRentApp/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using VideoRentApp.Models;
using VideoRentApp.Repos;

namespace VideoRentApp.Controllers
{
	public class MovieController : Controller
	{
		private readonly MovieRepository _movieRepository;
		public MovieController(MovieRepository movieRepository)
		{
			_movieRepository = movieRepository;
		}

		public IActionResult Index(int? id)
		{
			//var movies = _movieRepository.GetList();

			//if (id!=null)
			//{
			//	movies = movies.Where(i => i.RenterId == id).ToList();
			//}

			return View();
		}
		[HttpGet]
		public IActionResult Create()
		{
			return View();
		}
		[HttpPost]
		public IActionResult Create(Movie movie)
		{
			_movieRepository.Create(movie);
			return RedirectToAction(nameof(Index));
		}
		[HttpGet]
		public IActionResult Update(int id)
		{
			var movie = _movieRepository.GetById(id);
			return View(movie);
		}
		[HttpPost]
		public IActionResult Update(Movie movie)
		{
			_movieRepository.Update(movie);
			return RedirectToAction(nameof(Index));
		}

		public IActionResult Details(int id)
		{
			var result = _movieRepository.GetById(id);
			return View(result);
		}

		[HttpGet]
		public IActionResult Delete(int id)
		{
			var movie = _movieRepository.GetById(id);
			return View(movie);
		}

		[HttpPost]
		public IActionResult Delete(Movie movie)
		{
			_movieRepository.Delete(movie);
			return RedirectToAction(nameof(Index));
		}
	}
}

VideoRentApp/ViewComponents/RenterMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using VideoRentApp.Controllers;
using VideoRentApp.Data;
using VideoRentApp.Models;
using VideoRentApp.Repos;

namespace VideoRentApp.ViewComponents
{
	public class RenterMenuViewComponent : ViewComponent
	{
		private readonly RenterRepository _renterRepository;
		public RenterMenuViewComponent(RenterRepository renterRepository)
		{
			_renterRepository = renterRepository;
		}
		public IViewComponentResult Invoke()
		{
			if (RouteData.Values["action"].ToString()=="Index")
			{
				ViewBag.SelectedRenter = RouteData?.Values["id"];
			}
			var result = _renterRepository.GetList();
			return View(result);

		}


		// {controller}/{action}/{id?}
		// /home/index/3
		// /movie/index/3

		// RouteData.Values["controller"] ==> Controller/Movie
		// RouteData.Values["action"] ==> Action/Index
		// RouteData.Values["id"] ==> Id/3

		// Movie/Index sayfasina girdigimizde basta id girili olmadigi icin, yani herhangi bir renter secmedigimiz icin 
		// routedata herhangi bir id degeri almamis olacak. bu hatayi gidermek icin de routedata'nin sonuna '?' ekliyoruz


		// viewbag = gecici alan
	}
}

VideoRentApp/Views/Movie/Delete.cshtml
@model VideoRentApp.Models.Movie

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateRelease)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateRelease)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
    </dl>
    <form asp-action="Delete">
        <input type="hidden" asp-for="MovieId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

VideoRentApp/Views/Movie/Details.cshtml
@model VideoRentApp.Models.Movie

@{
	ViewData["Title"] = "Details";
}

<div>
	<h4>Details of Movie</h4>
	<hr />
	<dl class="row">
		<dt class="col-sm-2">
			<img src="~/img/@Html.DisplayFor(modelItem => modelItem.ImageUrl)" class="card-img" />
		</dt>
		<dd class="col-sm-10">
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Title)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Title)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Description)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Description)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Length)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Length) min.
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.DateRelease)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.DateRelease)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.Genre)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.Genre)
		</dd>
		<dt class="col-sm-2">
			@Html.DisplayNameFor(model => model.MainActress)
		</dt>
		<dd class="col-sm-10">
			@Html.DisplayFor(model => model.MainActress)
		</dd>
	</dl>
</div>
<div>
	<a asp-action="Edit" asp-route-id="@Model.MovieId">Edit</a> |
	<a asp-action="Index">Back to List</a><br />
	<a asp-action="Delete" asp-route-id="@Model.MovieId" class="btn btn-danger">Delete</a>

</div>

VideoRentApp/Views/Movie/Index.cshtml
@model IEnumerable<VideoRentApp.Models.Movie>


<div class="row">
	<div class="col-md-3">
		@await Component.InvokeAsync("RenterMenu")
	</div>
	<div class="col-md-9">
		@foreach (var item in Model)
		{
			<div class="card mb-3">
				<div class="row no-gutters">
					<div class="col-md-3">
						<img src="~/img/@Html.DisplayFor(modelItem => item.ImageUrl)" alt="@item.Title" class="card-img" />
					</div>
					<div class="col-md-9">
						<div class="card-body">
							<h5 class="card-title">
								<a asp-action="Details" asp-controller="Movie" asp-route-id="@item.MovieId">@Html.DisplayFor(modelItem => item.Title)</a>
							</h5>
							<p class="card-text">Length: @Html.DisplayFor(modelItem => item.Length) min.</p>
							<p class="card-text">
								<small class="text-muted">Date Release: @Html.DisplayFor(modelItem => item.DateRelease)</small>
							</p>
							<div class="rating-row" itemprop="aggregateRating" itemscope itemtype="http://schema.org/AggregateRating">
								<a class="icon" href="@Html.DisplayFor(modelitem => item.ImdbUrl)" title="IMDb" target="_blank"> <img src="/img/logo-imdb.svg" alt="IMDb" /></a>
							</div>
						</div>
					</div>
				</div>
			</div>
		}
	</div>
</div>

<!--<partial name="_movies" model="Model"/> movies'leri burada boyle gostermek yerine Views/Movie klasoru altina _movies isimli
	view ekleyip buradaki uzun kodu orada yazar ve partial ile burada cagirabilirdik, ama simdilik bu sekilde yazdik.
-->